---
name: test src/lib/_parser.bash
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  unit-test-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y uuid-runtime
      - name: run test harness
        run: sudo bash test/lib/_harness.bash test_parser.bats
