---
# Filename: .github/workflows/test_test_environment.yaml
name: Test Test Environment Workflow
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  setup-test-env-and-test-bats-common-setup:
    runs-on: ubuntu-latest
    container:
      image: robertportelli/test-rpi5-arch-installer:latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Run BATS Tests
        run: bats test/unit/test_common_setup.bats
