---
name: Test Device Fixture
on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  test-device-fixture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y uuid-runtime
      - name: run test harness
        run: sudo -E bash test/lib/_harness.bash test_device_fixture.bats
